dist: focal # Ubuntu 20.04
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12-dev"
# Travis CI doesn't support 3.13 yet
install:
  - python -m pip install pytest requests
script:
  - make test-travis
